AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy nodejs api on EC2
Metadata: 

Parameters: 
  EC2InstaceType:
    Type: String
  EC2AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Mappings: 

Conditions: 

Resources: 
  SecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}'
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
    Tags:
      - Key: Name
        Value: !Ref AWS::StackName
  InstanceRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        Effect: Allow
        Principal:
          Service:
            - "ec2.amazonaws.com"
        Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
    Tags:
      - Key: Name
        Value: !Ref AWS::StackName
  InstanceProfile:
  Type: "AWS::IAM::InstanceProfile"
  Properties:
    Roles:
      - Ref: InstanceRole
  Instance:
  Type: AWS::EC2::Instance
  CreationPolicy: 
    ResourceSignal:
      Timeout: PT15M
      Count: 1
  Metadata:
    AWS::CloudFormation::Init:
      config:
        packages: 
          yum:
            wget: []
            unzip: []
  Properties:
    ImageId: !Ref EC2AMI
    InstanceType: !Ref EC2InstanceType
    IamInstanceProfile: !Ref InstanceProfile
    Monitoring: true
    SecurityGroupIds:
      - !GetAtt SecurityGroup.GroupId 
    UserData:
      # ... 
    Tags:
      - Key: Name
        Value: !Ref AWS::StackName
Outputs: